

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Templates/OpenWorld
EditorStartupMap=/Game/Maps/Lv_Lobby.Lv_Lobby
TransitionMap=/Game/Maps/Lv_Transition.Lv_Transition

[/Script/Engine.RendererSettings]
r.AllowStaticLighting=False

r.GenerateMeshDistanceFields=True

r.DynamicGlobalIlluminationMethod=1

r.ReflectionMethod=1

r.SkinCache.CompileShaders=True

r.RayTracing=True

r.RayTracing.RayTracingProxies.ProjectEnabled=True

r.Substrate=True

r.Substrate.ProjectGBufferFormat=0

r.Shadow.Virtual.Enable=1

r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True

r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8

r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8
r.VirtualTextures=True
r.GPUSkin.Support16BitBoneIndex=True
r.GPUSkin.UnlimitedBoneInfluences=True
r.SkinCache.DefaultBehavior=0

SkeletalMesh.UseExperimentalChunking=1
r.DefaultFeature.AutoExposure=False
r.Mobile.AntiAliasing=2
r.AntiAliasingMethod=4

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6
-D3D11TargetedShaderFormats=PCD3D_SM5
+D3D11TargetedShaderFormats=PCD3D_SM5
Compiler=Default
AudioSampleRate=48000
AudioCallbackBufferFrameSize=1024
AudioNumBuffersToEnqueue=1
AudioMaxChannels=0
AudioNumSourceWorkers=4
SpatializationPlugin=
SourceDataOverridePlugin=
ReverbPlugin=
OcclusionPlugin=
CompressionOverrides=(bOverrideCompressionTimes=False,DurationThreshold=5.000000,MaxNumRandomBranches=0,SoundCueQualityIndex=0)
CacheSizeKB=65536
MaxChunkSizeOverrideKB=0
bResampleForDevice=False
MaxSampleRate=48000.000000
HighSampleRate=32000.000000
MedSampleRate=24000.000000
LowSampleRate=12000.000000
MinSampleRate=8000.000000
CompressionQualityModifier=1.000000
AutoStreamingThreshold=0.000000
SoundCueCookQualityIndex=-1

[/Script/LinuxTargetPlatform.LinuxTargetSettings]
-TargetedRHIs=SF_VULKAN_SM5
+TargetedRHIs=SF_VULKAN_SM6

[/Script/MacTargetPlatform.MacTargetSettings]
-TargetedRHIs=SF_METAL_SM5
+TargetedRHIs=SF_METAL_SM6

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/WorldPartitionEditor.WorldPartitionEditorSettings]
CommandletClass=Class'/Script/UnrealEd.WorldPartitionConvertCommandlet'

[/Script/Engine.UserInterfaceSettings]
bAuthorizeAutomaticWidgetVariableCreation=False
FontDPIPreset=Standard
FontDPI=72

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/Murphy")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_Blank",NewGameName="/Script/Murphy")

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=C6219FDC43EB2BBDD40D6DB265D941B3
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=


[CoreRedirects]
+ClassRedirects=(OldName="/Script/Murphy.VoiceRecordComponent",NewName="/Script/Murphy.VoiceRecorderComponent")
+PropertyRedirects=(OldName="/Script/Murphy.VoiceChatActor.VoiceRecorderComponent",NewName="/Script/Murphy.VoiceChatActor.VoiceRecorderComp")
+ClassRedirects=(OldName="/Script/Murphy.LevelManagerSubsystem",NewName="/Script/Murphy.LevelStreamingSubsystem")
+ClassRedirects=(OldName="/Script/Murphy.LevelEnterToastPopup",NewName="/Script/Murphy.LevelEnterToastPopupWidget")
+FunctionRedirects=(OldName="/Script/Murphy.LevelEnterToastPopupWidget.SetLevelName",NewName="/Script/Murphy.LevelEnterToastPopupWidget.SetUp")
+PropertyRedirects=(OldName="/Script/Murphy.BagPopupWidget.Anim_SlideUp",NewName="/Script/Murphy.BagPopupWidget.Anim_BagSlideUp")
+PropertyRedirects=(OldName="/Script/Murphy.PhonePopupWidget.WBP_Translation",NewName="/Script/Murphy.PhonePopupWidget.WBP_Translate")
+PropertyRedirects=(OldName="/Script/Murphy.CinematicOverlayWidget.BlackImage",NewName="/Script/Murphy.CinematicOverlayWidget.Img_Black")
+PropertyRedirects=(OldName="/Script/Murphy.CinematicOverlayWidget.MediaImage",NewName="/Script/Murphy.CinematicOverlayWidget.Img_Media")
+EnumRedirects=(OldName="/Script/Murphy.EPlayerViewState",ValueChanges=(("ThirdPersonTalk","ThirdPersonFocus")))
+ClassRedirects=(OldName="/Script/Murphy.NetSubsystem",NewName="/Script/Murphy.AIBridgeSubsystem")
+PropertyRedirects=(OldName="/Script/Murphy.LobbyUI.btn_SinglePlay",NewName="/Script/Murphy.LobbyUI.Btn_SinglePlay")
+PropertyRedirects=(OldName="/Script/Murphy.LobbyUI.btn_MultiPlay",NewName="/Script/Murphy.LobbyUI.Btn_MultiPlay")
+PropertyRedirects=(OldName="/Script/Murphy.LobbyUI.btn_Achievement",NewName="/Script/Murphy.LobbyUI.Btn_Achievement")
+PropertyRedirects=(OldName="/Script/Murphy.LobbyUI.btn_Option",NewName="/Script/Murphy.LobbyUI.Btn_Option")
+PropertyRedirects=(OldName="/Script/Murphy.LobbyUI.btn_Quit",NewName="/Script/Murphy.LobbyUI.Btn_Quit")
+PropertyRedirects=(OldName="/Script/Murphy.SessionInfoWidget.Txt_HostName_1",NewName="/Script/Murphy.SessionInfoWidget.Txt_PlayerCountInfo")
+PropertyRedirects=(OldName="/Script/Murphy.LobbyUI.Btn_CreateSession",NewName="/Script/Murphy.LobbyUI.Btn_ToggleSessionSetting")
+PropertyRedirects=(OldName="/Script/Murphy.LobbyUI.Btn_ShowSessionSetting",NewName="/Script/Murphy.LobbyUI.Btn_ToggleSessionSetting")
+FunctionRedirects=(OldName="/Script/Murphy.LobbyUI.OnCreateSessionButtonClicked",NewName="/Script/Murphy.LobbyUI.OnToggleSessionSettingButtonClicked")
+PropertyRedirects=(OldName="/Script/Murphy.WriteArrivalCardWidget.ArrivalCardItem",NewName="/Script/Murphy.WriteArrivalCardWidget.WBP_ArrivalCard")
+PropertyRedirects=(OldName="/Script/Murphy.SessionPlayerStateWidget.Txt_PlayerReadyStart",NewName="/Script/Murphy.SessionPlayerStateWidget.Txt_PlayerReady")
+ClassRedirects=(OldName="/Script/Murphy.PlayReportWidget",NewName="/Script/Murphy.PlayReportMainWidget")
+PropertyRedirects=(OldName="/Script/Murphy.PlayReportItemWidget.DynamicProgresMaterial",NewName="/Script/Murphy.PlayReportItemWidget.DynamicProgressMaterial")
+FunctionRedirects=(OldName="/Script/Murphy.ScenarioCategoryButtonWidget.OnCheckBoxChanged",NewName="/Script/Murphy.ScenarioCategoryButtonWidget.OnCategoryChanged")
+ClassRedirects=(OldName="/Script/Murphy.FeedbackWidget",NewName="/Script/Murphy.FeedbackMainWidget")
+PropertyRedirects=(OldName="/Script/Murphy.FeedbackCardWidget.txt_Suggestions",NewName="/Script/Murphy.FeedbackCardWidget.txt_PracticePrompt")
+PropertyRedirects=(OldName="/Script/Murphy.PlayReportMainWidget.txt_FinalRecommendation",NewName="/Script/Murphy.PlayReportMainWidget.txt_Result")


[/Script/UdpMessaging.UdpMessagingSettings]
EnableTransport=False

[Core.Log]
LogOnline=Verbose

;-------------------------------------- server setup -----------------------------------

[/Script/Engine.GameEngine]
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="OnlineSubsystemSteam.SteamNetDriver",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")

[OnlineSubsystem]
DefaultPlatformService=NULL
;DefaultPlatformService=Steam
bUseLanBeacon=true

[OnlineSubsystemSteam]
bEnabled=true
SteamDevAppId=480

[/Script/OnlineSubsystemSteam.SteamNetDriver]
NetConnectionClassName="OnlineSubsystemSteam.SteamNetConnection"
;--------------------------------------------------------------------------------------------

[SystemSettings]
; PIE에서 SeamlessTravel을 허용해 ServerTravel 시 PlayerState(SelectedCharacter 등)가 유지되도록 함
net.AllowPIESeamlessTravel=1
r.Streaming.PoolSize=2000

